name: Barrels
description: 此插件為繁體翻譯版, 原作者"TheBusyBiscuit , John000708".
authors: [John000708, TheBusyBiscuit]
version: ${project.version}

main: me.john000708.barrels.Barrels
api-version: 1.14

depend: [Slimefun]